config/routes.rb
Rails.application.routes.draw do
  resources :server_deploys
  resources :servers
  post "/api/deploy_log", to: "api#deploy_log"
  post "api/heroku_deploy_log_hook", to: "api#heroku_deploy_log_hook"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "servers#index"

  resources :slack do
    collection do
      post :staging
      post :slash_super_staging
      post :super_staging_event
      post :super_staging_interactivity
    end
  end
end

app/models/server.rb
class Server < ApplicationRecord
  has_many :deploys, class_name: "ServerDeploy"

  scope :by_alias, ->(aliaz) do
    where(git_remote: aliaz).or(where(abbreviation: aliaz))
  end

  def self.find_by_alias(aliaz)
    by_alias(aliaz).first
  end

  def thumbnail_image
    return nil #this is breaking?
    if !Rails.env.production?
      return nil
    end

    options = {
        url:                 server_url,
        thumbnail_max_width: 400,
        viewport:            "10247/768",
        fullpage:            true,
        unique:              Time.now.to_i / 60 # forces a unique request at most once an hour
    }
    url     = Url2png.new(options).url
    puts url

    return url
  end

  def dynamic_status

  end

  def live_url
    server_url
  end

  def reserved?
    reserved_until.present? && reserved_until > Time.now
  end

  def recently_reserved?
    reserved_until.present? && (6.hours.ago..Time.now).include?(reserved_until)
  end

  def free?
    reserved_until.blank? || reserved_until < 6.hours.ago
  end

  def status_emoji
    if reserved?
      ':x:'
    elsif recently_reserved?
      ':warning:'
    else
      ''
    end
  end

  def platform_emoji
    case platform&.downcase
    when 'rs', 'repairshopr'
      ':rs:'
    when 'syncro'
      ':syncro:'
    when 'kabuto'
      ':kabuto:'
    else
      ''
    end
  end

  def kabuto?
    platform.downcase == 'kabuto'
  end

  def repairshopr?
    platform.downcase.in? %w[rs repairshopr]
  end

  alias_method :rs?, :repairshopr?

  def syncro?
    platform.downcase == 'syncro'
  end

  def rsyn?
    repairshopr? || syncro?
  end

  def reserve!(purpose, hours, user)
    update!(reserved_for: purpose, reserved_until: (hours.to_i.nonzero? || 1).hours.from_now, reserved_by: user)
  end

  def release!
    update!(reserved_until: nil)
  end
end

#------------------------------------------------------------------------------
# Server
#
# Name            SQL Type             Null    Default Primary
# --------------- -------------------- ------- ------- -------
# id              INTEGER              false           true   
# name            varchar              true            false  
# description     varchar              true            false  
# logo_url        varchar              true            false  
# status          varchar              true            false  
# reserved_until  datetime             true            false  
# reserved_for    varchar              true            false  
# slack_channel   varchar              true            false  
# created_at      datetime             false           false  
# updated_at      datetime             false           false  
# server_url      varchar              true            false  
# git_remote      varchar              true            false  
# jira_iframe_url varchar              true            false  
# platform        varchar              true            false  
# reserved_by     varchar              true            false  
# abbreviation    varchar              true            false  
#
#------------------------------------------------------------------------------

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: [:show, :edit, :update, :destroy]

  # GET /servers
  # GET /servers.json
  def index
    @servers = Server.order(:name)
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
  end

  # GET /servers/new
  def new
    @server = Server.new
  end

  # GET /servers/1/edit
  def edit
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(server_params)

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
        format.json { render :show, status: :created, location: @server }
      else
        format.html { render :new }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servers/1
  # PATCH/PUT /servers/1.json
  def update
    respond_to do |format|
      copied_params = server_params.dup
      if server_params[:reserved_until].present?
        new_time = Time.now+(copied_params[:reserved_until].to_i).hours
        copied_params[:reserved_until] = new_time
        puts "MUNGED: #{copied_params}"
      end

      if @server.update(copied_params)
        format.html { redirect_to root_path, notice: 'Server was successfully updated.' }
        format.json { render :show, status: :ok, location: @server }
      else
        format.html { render :edit }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server.destroy
    respond_to do |format|
      format.html { redirect_to servers_url, notice: 'Server was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_server
      @server = Server.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def server_params
      params.require(:server).permit(:name, :description,
                                     :logo_url, :status, :reserved_until,
                                     :reserved_for, :slack_channel,
                                     :server_url, :git_remote, :jira_iframe_url)
    end
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/_form.html.erb
<%= form_with(model: server, local: true) do |form| %>
  <% if server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
      <% server.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :server_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :server_description %>
  </div>

  <div class="field">
    <%= form.label :logo_url %>
    <%= form.text_field :logo_url, id: :server_logo_url %>
  </div>

  <div class="field">
    <%= form.label :server_url %>
    <%= form.text_field :server_url, id: :server_server_url %>
  </div>

  <div class="field">
    <%= form.label :git_remote %>
    <%= form.text_field :git_remote, id: :server_git_remote%>
  </div>

  <div class="field">
    <%= form.label :jira_iframe_url %>
    <%= form.text_field :jira_iframe_url, id: :jira_iframe_url %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/servers/edit.html.erb
<h1>Editing Server</h1>

<%= render 'form', server: @server %>

<%= link_to 'Show', @server %> |
<%= link_to 'Back', servers_path %>

app/views/servers/index.html.erb
<p id="notice"><%= notice %></p>


<div class="row">
  <% @servers.each do |server| %>
    <div class="col-sm-3 col-xs-6" style="padding-bottom: 20px;">
      <div class="bs-component dashboard-card">
        <div class="card our-card">
          <h3 class="<%= (server.reserved_until.present? && server.reserved_until > Time.now) ? 'card-warning' : 'card-info' %> card-header"><%# server.reserved_until%></h3>
          <h3 class="card-header"><%= image_tag(server.name.to_s.include?("Syn") ? 'syncro-icon.png' : "logo-square-500px.png", skip_pipeline: true, style: "max-height: 25px; padding-right: 10px;") %><%= server.name %></h3>
          <div class="card-block">
            <h5 class="card-title">Branch: <%= server.deploys.last.try(:git_branch) || "master" %></h5>
            <h6 class="card-subtitle text-muted"><%= server.dynamic_status %></h6>
          </div>
          <% if server.jira_iframe_url %>
            <iframe src="<%= server.jira_iframe_url %>"></iframe>
          <% end %>
          <div class="card-block">
            <p class="card-text alert-warning">
              <% if server.reserved_until.present? && server.reserved_until > Time.now %>
                Until: <%= l server.reserved_until, format: :short%><br>
                <%= server.reserved_for %>
              <% end %>
            </p>
            <p class="card-text" title="<%= server.deploys.last.try(:git_commit_message) %>"><%= server.deploys.last.try(:git_commit_message).to_s.truncate(80) %></p>
            <a href="https://<%= server.server_url %>" class="card-link">Server link</a>
            <%= link_to "Reserve", "#", class: "card-link bhvCardReserve bhvCardReserve-#{server.id}", data: {server: server.id}  %>
            <div class="bhvHideReserveForm-<%= server.id %>" style="display: none;">
              <%= form_with(model: server, local: true) do |form| %>

                <div class="field">
                  <%= form.label "Reserved for (Reason)" %>
                  <%= form.text_field :reserved_for %>
                </div>

                <div class="field">
                  <%= form.label :reserve_time %>

                  <%= form.select(:reserved_until) do %>
                    <% [['1 Hr', 1], ['2 Hrs', 2], ['8 Hrs', 8], ['1 Day', 24], ['2 Days', 48], ['7 Days', 168]].each do |c| -%>
                      <%= content_tag(:option, c.first, value: c.last) %>
                    <% end %>
                  <% end %>
                </div>


                <div class="actions">
                  <%= form.submit %>
                </div>
              <% end %>

            </div>
          </div>
          <div class="card-footer text-xs-center">
            <%= time_ago_in_words(server.deploys.last.try(:created_at) || server.updated_at) %> Ago
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script>
  $( document ).ready(function() {
    console.log( "ready!" );
    $( ".bhvCardReserve" ).click(function(e) {
      e.preventDefault()
      console.log( "Handler for .click() called.",e.currentTarget.dataset.server );
      $(".bhvHideReserveForm-"+e.currentTarget.dataset.server).show()
    });
  });
</script>

<br>

<%= link_to 'New Server', new_server_path %>

app/views/servers/new.html.erb
<h1>New Server</h1>

<%= render 'form', server: @server %>

<%= link_to 'Back', servers_path %>

app/views/servers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @server.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @server.description %>
</p>

<p>
  <strong>Logo url:</strong>
  <%= @server.logo_url %>
</p>

<p>
  <strong>Status:</strong>
  <%= @server.status %>
</p>

<p>
  <strong>Reserved until:</strong>
  <%= @server.reserved_until %>
</p>

<p>
  <strong>Reserved for:</strong>
  <%= @server.reserved_for %>
</p>

<p>
  <strong>Slack channel:</strong>
  <%= @server.slack_channel %>
</p>

<p>
  <strong>Git Remote:</strong>
  <%= @server.git_remote %>
</p>

<%= link_to 'Edit', edit_server_path(@server) %> |
<%= link_to 'Back', servers_path %>