config/routes.rb
Rails.application.routes.draw do
  resources :server_deploys
  resources :servers
  post "/api/deploy_log", to: "api#deploy_log"
  post "api/heroku_deploy_log_hook", to: "api#heroku_deploy_log_hook"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "servers#index"

  resources :slack do
    collection do
      post :staging
      post :slash_super_staging
      post :super_staging_event
      post :super_staging_interactivity
    end
  end
end

app/models/server_deploy.rb
class ServerDeploy < ApplicationRecord
  belongs_to :server

  def self.create_from_params(server: nil, params: nil)
    puts "IN_CREATE: #{params}"
    return {save: false, params: params} unless params[:git_branch]

    deploy                    = server.deploys.new
    deploy.git_branch         = params[:git_branch]
    deploy.git_user           = params[:git_user]
    deploy.git_commit_message = params[:git_commit_message]
    deploy.commit_hash        = params[:commit_hash]
    deploy.save!

    deploy
  end

  def git_url
    if server.rsyn?
      "https://github.com/RepairShopr/RepairShopr/commit/#{commit_hash}"
    elsif server.kabuto?
      "https://github.com/repairtech/kabuto/commit/#{commit_hash}"
    else
      ''
    end
  end

  def slack_git_link
    "<#{git_url}|#{git_branch.strip}>"
  end
end

#------------------------------------------------------------------------------
# ServerDeploy
#
# Name               SQL Type             Null    Default Primary
# ------------------ -------------------- ------- ------- -------
# id                 INTEGER              false           true   
# server_id          integer              true            false  
# git_branch         varchar              true            false  
# commit_hash        varchar              true            false  
# git_user           varchar              true            false  
# created_at         datetime             false           false  
# updated_at         datetime             false           false  
# git_commit_message text                 true            false  
#
#------------------------------------------------------------------------------

app/controllers/server_deploys_controller.rb
class ServerDeploysController < ApplicationController
  before_action :set_server_deploy, only: [:show, :edit, :update, :destroy]

  # GET /server_deploys
  # GET /server_deploys.json
  def index
    @server_deploys = ServerDeploy.all
  end

  # GET /server_deploys/1
  # GET /server_deploys/1.json
  def show
  end

  # GET /server_deploys/new
  def new
    @server_deploy = ServerDeploy.new
  end

  # GET /server_deploys/1/edit
  def edit
  end

  # POST /server_deploys
  # POST /server_deploys.json
  def create
    @server_deploy = ServerDeploy.new(server_deploy_params)

    respond_to do |format|
      if @server_deploy.save
        format.html { redirect_to @server_deploy, notice: 'Server deploy was successfully created.' }
        format.json { render :show, status: :created, location: @server_deploy }
      else
        format.html { render :new }
        format.json { render json: @server_deploy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /server_deploys/1
  # PATCH/PUT /server_deploys/1.json
  def update
    respond_to do |format|
      if @server_deploy.update(server_deploy_params)
        format.html { redirect_to @server_deploy, notice: 'Server deploy was successfully updated.' }
        format.json { render :show, status: :ok, location: @server_deploy }
      else
        format.html { render :edit }
        format.json { render json: @server_deploy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /server_deploys/1
  # DELETE /server_deploys/1.json
  def destroy
    @server_deploy.destroy
    respond_to do |format|
      format.html { redirect_to server_deploys_url, notice: 'Server deploy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_server_deploy
      @server_deploy = ServerDeploy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def server_deploy_params
      params.require(:server_deploy).permit(:server_id, :git_branch, :commit_hash, :git_user)
    end
end

app/helpers/server_deploys_helper.rb
module ServerDeploysHelper
end

app/views/server_deploys/_form.html.erb
<%= form_with(model: server_deploy, local: true) do |form| %>
  <% if server_deploy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(server_deploy.errors.count, "error") %> prohibited this server_deploy from being saved:</h2>

      <ul>
      <% server_deploy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :server_id %>
    <%= form.number_field :server_id, id: :server_deploy_server_id %>
  </div>

  <div class="field">
    <%= form.label :git_branch %>
    <%= form.text_field :git_branch, id: :server_deploy_git_branch %>
  </div>

  <div class="field">
    <%= form.label :commit_hash %>
    <%= form.text_field :commit_hash, id: :server_deploy_commit_hash %>
  </div>

  <div class="field">
    <%= form.label :git_user %>
    <%= form.text_field :git_user, id: :server_deploy_git_user %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/server_deploys/edit.html.erb
<h1>Editing Server Deploy</h1>

<%= render 'form', server_deploy: @server_deploy %>

<%= link_to 'Show', @server_deploy %> |
<%= link_to 'Back', server_deploys_path %>

app/views/server_deploys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Server Deploys</h1>

<table>
  <thead>
    <tr>
      <th>Server</th>
      <th>Git branch</th>
      <th>Commit hash</th>
      <th>Git user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @server_deploys.each do |server_deploy| %>
      <tr>
        <td><%= server_deploy.server_id %></td>
        <td><%= server_deploy.git_branch %></td>
        <td><%= server_deploy.commit_hash %></td>
        <td><%= server_deploy.git_user %></td>
        <td><%= link_to 'Show', server_deploy %></td>
        <td><%= link_to 'Edit', edit_server_deploy_path(server_deploy) %></td>
        <td><%= link_to 'Destroy', server_deploy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Server Deploy', new_server_deploy_path %>

app/views/server_deploys/new.html.erb
<h1>New Server Deploy</h1>

<%= render 'form', server_deploy: @server_deploy %>

<%= link_to 'Back', server_deploys_path %>

app/views/server_deploys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Server:</strong>
  <%= @server_deploy.server_id %>
</p>

<p>
  <strong>Git branch:</strong>
  <%= @server_deploy.git_branch %>
</p>

<p>
  <strong>Commit hash:</strong>
  <%= @server_deploy.commit_hash %>
</p>

<p>
  <strong>Git user:</strong>
  <%= @server_deploy.git_user %>
</p>

<%= link_to 'Edit', edit_server_deploy_path(@server_deploy) %> |
<%= link_to 'Back', server_deploys_path %>